### ISSUE TITLE
User "Hallier" reported rendering issues.

### ISSUE THREAD

**Issue by Scrivener07** [Scrivener07/FO4_Overlays#16]
@**[Hallier](https://www.nexusmods.com/users/50928766)**
> Alright, since there isn't a bug page; whenever I put my gasmask with goggles on, 2/3 of my screen stops rendering objects or menus ingame and shows through the world (basically it shows the classic skybox with nothing in it.) No idea WHY, I have zero visual mods on my pip boy or menus, I DO have a sorting mod, and I DO have textures installed. Other than that, I have zero HUD modifiers and zero ENBs or lighting changes besides Darker Nights 1.11p6. I don't have any conflicts with any mods though. Gonna continue testing. I'll let you know if I get it to work.

**Comment by Barerock** [comment]
Hey. Hallier again. Different name. 
The problem persists even after turning off the only shader (darker nights) I have. Not sure what else could cause this? Is your mod a type of UI? An edition to the HUD? Or is it a shader like I think it is?

**Comment by Scrivener07** [comment]
@Barerock This has been fixed as of commit 0bde36b. The fixes are included with version [1.2.0](https://github.com/Scrivener07/FO4_Overlays/releases/tag/v1.2.0).
